# Generated by Django 5.1.15 on 2026-04-20 02:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('shipping_line1', models.CharField(default='', max_length=200)),
                ('shipping_line2', models.CharField(blank=True, default='', max_length=200)),
                ('shipping_city', models.CharField(default='', max_length=120)),
                ('shipping_state', models.CharField(blank=True, default='', max_length=120)),
                ('shipping_postal_code', models.CharField(default='', max_length=30)),
                ('shipping_country', models.CharField(default='US', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('submitted_to_shapeways', 'Submitted to Shapeways'), ('fulfilled', 'Fulfilled'), ('failed', 'Failed')], default='pending', max_length=40)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=120)),
                ('shapeways_order_id', models.CharField(blank=True, default='', max_length=120)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=120)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, default='')),
                ('stl_file_reference', models.CharField(blank=True, default='', help_text='Shapeways model id, URL, or local path to STL.', max_length=500)),
                ('category', models.CharField(choices=[('planter', 'Planter'), ('other', 'Other')], default='planter', max_length=40)),
                ('in_stock', models.BooleanField(default=True)),
                ('meshy_task_id', models.CharField(blank=True, default='', max_length=120)),
                ('shapeways_model_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.product')),
            ],
        ),
    ]
