# Generated by Django 5.1.15 on 2026-04-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_model_and_merchandising'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_functional_planter',
            field=models.BooleanField(default=False, help_text='Passed the mesh QC as a usable planter (watertight or hollow with drainage & pot-fit).'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='Nylon PA12 / Versatile Plastic', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_source',
            field=models.CharField(blank=True, default='', help_text="'shapeways_quote' or 'estimated'.", max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='qc_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='shapeways_print_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-unit print cost from Shapeways quote (or heuristic estimate).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_cm3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mesh volume in cm³ after QC-time scaling.', max_digits=10, null=True),
        ),
    ]
