# Generated by Django 5.1.15 on 2026-04-20 16:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetPortrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('pet_name', models.CharField(blank=True, default='', max_length=80)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], default='dog', max_length=16)),
                ('uploaded_photo', models.ImageField(blank=True, null=True, upload_to='portrait_uploads/')),
                ('photo_quality_score', models.IntegerField(default=0, help_text='0-100')),
                ('photo_issues', models.JSONField(blank=True, default=list)),
                ('meshy_variants', models.JSONField(blank=True, default=list)),
                ('selected_variant_task_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('photo_uploaded', 'Photo uploaded'), ('photo_rejected', 'Photo rejected'), ('deposit_pending', 'Deposit pending'), ('generating', 'Generating variants'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('fulfilled', 'Fulfilled'), ('refunded', 'Refunded')], default='photo_uploaded', max_length=32)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_payment_intent_id', models.CharField(blank=True, default='', max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortraitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('material', models.CharField(choices=[('plastic', 'Plastic (Versatile Plastic)'), ('bronze', 'Bronze'), ('silver', 'Sterling Silver'), ('gold_14k', '14K Gold'), ('platinum', 'Platinum')], max_length=16)),
                ('size_mm', models.PositiveIntegerField(help_text='Longest dimension in millimeters')),
                ('retail_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('design_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('metal_spot_price_snapshot', models.JSONField(blank=True, default=dict)),
                ('shapeways_cost_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estimated_metal_weight_g', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('shipping_name', models.CharField(blank=True, default='', max_length=120)),
                ('shipping_address1', models.CharField(blank=True, default='', max_length=200)),
                ('shipping_address2', models.CharField(blank=True, default='', max_length=200)),
                ('shipping_city', models.CharField(blank=True, default='', max_length=100)),
                ('shipping_region', models.CharField(blank=True, default='', max_length=100)),
                ('shipping_postcode', models.CharField(blank=True, default='', max_length=30)),
                ('shipping_country', models.CharField(blank=True, default='US', max_length=2)),
                ('shapeways_model_id', models.CharField(blank=True, default='', max_length=120)),
                ('shapeways_order_id', models.CharField(blank=True, default='', max_length=120)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=120)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('submitted', 'Submitted to Shapeways'), ('in_production', 'In production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='portraits.petportrait')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
